### ISSUE TITLE
Support filters for Keys in YAML-Files

### ISSUE THREAD

**Issue by denglertai** [denglertai/gonfig#39]
Assume the following yaml config:
```yaml
${USERNAME}:
  hash: "${PASSWORD | bcrypt}"
  backend_roles:
  - "admin"
  description: "Demo admin user"
```

Even though this a valid yaml, by now it is not possible to replace ${USERNAME} with the env variable being available.

Task:
- [x] Add yaml keys to the list of replaceable things in yaml trees
- [x] Ensure the functionality using unittests
